var express = require('express');
var router = express.Router();
var MongoClient = require('mongodb').MongoClient,
    assert = require('assert');

//const dbHost = 'mongodb://localhost:27017/logSystem';
const dbHost = 'mongodb://mongoOne:27017,mongoTwo:27018,mongoThree:27019/logSystem?replicaSet=logdb-replica-set';

/*Status check*/
router.get('/', function(req, res) {
    //res.send({ping:'hello this is server and I am alive!'});
    res.sendStatus(200);
});



/* GET all user activity data. */
router.get('/useractivitydata', function(req, res, next) {

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    //console.log("Successfully connected to the db server");

    db.collection('useractivitylogs').find({}).toArray(function(err, docs){

      //console.log(docs);
      var msg = [];

      docs.forEach(function(doc){
        msg.push(doc);

      });
      db.close();
      res.json(msg);
    });
    console.log("Called find()");
  });
});

/* GET counts for login */
router.get('/logincount', function(req, res, next) {

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    //console.log("Successfully connected to the db server");

      //count logins
      //db.useractivitylogs.find({"meta.httpRequest.requestUrl":"/login"}).count();
      db.collection('useractivitylogs').find({}).toArray(function(err, docs){

        //console.log(docs);
        var logincounter = 0
        var length = docs.length;
        //console.log(length)
        for(var i = 0; i<length; i++){

          //console.log(docs[i].meta.httpRequest.requestUrl);
          if(docs[i].meta.httpRequest.requestUrl == "/logout"){
            logincounter++
          }
        }

        db.close();
        res.json(logincounter);
      });
});
});


/* GET counts for registration/signup */
router.get('/signupcount', function(req, res, next) {

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    //console.log("Successfully connected to the db server");

      //count logins
      //db.useractivitylogs.find({"meta.httpRequest.requestUrl":"/login"}).count();
      db.collection('useractivitylogs').find({}).toArray(function(err, docs){

        //console.log(docs);
        var regcounter = 0
        var length = docs.length;
        //console.log(length)
        for(var i = 0; i<length; i++){

          //console.log(docs[i].meta.httpRequest.requestUrl);
          if(docs[i].meta.httpRequest.requestUrl == "/signup"){
            regcounter++
          }
        }

        db.close();
        res.json(regcounter);

      });
});
});

/* GET counts for Payments page visits */

//Note: The payments api logs this data only if the user has completed a payment Successfully.
//

router.get('/paymentcount', function(req, res, next) {
  //var logincounter = 0;

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    //console.log("Successfully connected to the db server");

      //count visits to payment page.
      //db.useractivitylogs.find({"requestUrl":"/payment"}).count();
      db.collection('paymentactivitylogs').find({}).toArray(function(err, docs){

        //console.log(docs);
        var paycounter = 0
        var length = docs.length;
        //console.log(length)
        for(var i = 0; i<length; i++){

          //console.log(docs[i].requestUrl);
          if(docs[i].requestUrl == "/payment"){
            paycounter++;
          }
        }

        db.close();
        res.json(paycounter);

      });
});
});


/* GET Total revenue generated by cart. */


router.get('/totalrevenue', function(req, res, next) {

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    //console.log("Successfully connected to the db server");
      //count visits to payment page.
      //db.useractivitylogs.find({"requestUrl":"/payment"}).count();
      db.collection('paymentactivitylogs').find({}).toArray(function(err, docs){

        //console.log(docs);
        var revenue = 0

        var length = docs.length;
        //console.log(length)
        for(var i = 0; i<length; i++){

          //console.log(docs[i].requestUrl);
          if(docs[i].requestUrl == "/payment"){
            revenue+=docs[i].amount
          }
        }

        db.close();
        //res.json(msg);
        res.json(revenue);

      });
});
});


/* GET all the payment data generated by cart. */

router.get('/paymentdata', function(req, res, next) {

  MongoClient.connect(dbHost , function(err, db){
    assert.equal(null, err);
    console.log("Successfully connected to the db server");

    db.collection('paymentactivitylogs').find({}).toArray(function(err, docs){

      var data = [];

      docs.forEach(function(doc){
        data.push(doc);

      });
      db.close();
      res.json(data);
    });

  });

  //res.render('index', { body: msg });
  //res.render(msg);
  //res.send(docs);

});



//get users location details.
//show users on a map.


function myFunction() {
	var city_names = ["Aberdeen", "Mumbai"];
    var rand = city_names[Math.floor(Math.random() * city_names.length)];

    document.getElementById("demo").innerHTML = rand;
}



module.exports = router;
